# Generated by Django 6.0.1 on 2026-01-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_driver_online',
            field=models.BooleanField(default=False),
        ),
    ]
